# Generated by Django 5.1.1 on 2026-10-02 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rega', models.CharField(help_text='Código oficial de Registro de Explotaciones Agrarias', max_length=20, unique=True, verbose_name='Código REGA')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la explotación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Explotación',
                'verbose_name_plural': 'Explotaciones',
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la finca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='ganaderia.explotacion', verbose_name='Explotación')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crotal', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='El crotal debe ser exactamente 4 dígitos numéricos', regex='^\\d{4}$')], verbose_name='Crotal')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('raza', models.CharField(default='CRUZADO', max_length=50, verbose_name='Raza')),
                ('estado_vital', models.CharField(choices=[('VIVO', 'Vivo'), ('BAJA', 'Baja')], default='VIVO', max_length=5, verbose_name='Estado vital')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('motivo_baja', models.CharField(blank=True, max_length=200, verbose_name='Motivo de baja')),
                ('sub_ubicacion', models.CharField(choices=[('PASTO', 'Pasto'), ('CEBADERO', 'Cebadero'), ('APARTADO', 'Apartado')], default='PASTO', max_length=10, verbose_name='Sub-ubicación (recinto)')),
                ('fecha_entrada_cebadero', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada al cebadero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='ganaderia.animal', verbose_name='Madre')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='ganaderia.finca', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['crotal'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateField(verbose_name='Fecha del parto')),
                ('alerta_intervalo', models.BooleanField(default=False, verbose_name='Alerta de intervalo (< 270 días)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_origen', to='ganaderia.animal', verbose_name='Cría')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos_como_madre', to='ganaderia.animal', verbose_name='Madre')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-fecha_parto'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ROJO', 'Alerta Roja - Intervalo Parto < 270 días'), ('AMARILLO', 'Alerta Amarilla - Crotal histórico reutilizado'), ('INFO', 'Información')], max_length=10, verbose_name='Tipo de incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='ganaderia.animal', verbose_name='Animal')),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='ganaderia.parto', verbose_name='Parto relacionado')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(choices=[('PASTO', 'Pasto'), ('CEBADERO', 'Cebadero'), ('APARTADO', 'Apartado')], max_length=10, verbose_name='Tipo de ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='ganaderia.finca', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['finca', 'tipo_ubicacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_vital', 'VIVO')), fields=('crotal',), name='unique_crotal_vivo'),
        ),
    ]
