# Generated by Django 5.1.1 on 2026-10-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='cria2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_origen_segundo', to='ganaderia.animal', verbose_name='Cría 2 (Gemelar)'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='cria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_origen', to='ganaderia.animal', verbose_name='Cría 1'),
        ),
    ]
