# Generated by Django 5.1.1 on 2026-10-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0002_parto_cria2_alter_parto_cria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='ganaderia.finca', verbose_name='Finca'),
        ),
    ]
