# Generated by Django 5.1.1 on 2026-10-03 11:22

import ganaderia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0003_alter_animal_finca'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='animal',
            name='unique_crotal_vivo',
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, validators=[ganaderia.models.validar_no_futuro], verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_entrada_cebadero',
            field=models.DateField(blank=True, null=True, validators=[ganaderia.models.validar_no_futuro], verbose_name='Fecha de entrada al cebadero'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_nacimiento',
            field=models.DateField(validators=[ganaderia.models.validar_no_futuro], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_parto',
            field=models.DateField(validators=[ganaderia.models.validar_no_futuro], verbose_name='Fecha del parto'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_vital', 'VIVO')), fields=('crotal',), name='unique_active_crotal_per_farm'),
        ),
    ]
